language: node_js
node_js:
  - 10
  - 12
script: ./scripts/build.js
env:
  - secure: "KVyUinZk/jjCtgdWTm2aJIqG6SGnaPWrkkck3RfXgZouKSmnz6V3NjBMSjg7IA9m20QGLN5f1E+FlJAlT+fXuhjG3kb6xs5Fvrzf4nCyzP9w3r2V3+nIbIQ48WyqqTWI6VZbQU2Tl9AlKka1lHkCC28kIEXxEcB8O89qd8MLErtKrOfoRISpQBUaUeo2aukyKdWSMfEev0z2BgTqLogcRNAepySqGV0lyU3TZogc4Wl0zFq3ekB8s2Boz7tzPYkkvtOgqZZtp3bvs8fOglkGmvixyrNqyqi5Fegw2UBqsKirq5quY9U/tdAuXDoioV8gOo+X4O3n0GJQHKSu2F/ALiEIFGWHM6lK//mii4htlD9S6qGsANYPUjti1mIY1MKyzXn3pGKM7+6zMffGMyYL+DGtKt32/PkX3TN0AA+/eUVCkmlhOFRL5IDYdvzXkqcEpUOQByATBZAwQQMcTdkplUftfYEE3CVUTTHS+oJApJT99Qc5EyexZUCU/EChB9xctE+GPofvfwAGdtZiSKaATWFc0orF0FI8cRYFauslL2tO27Rmi/ZIWOB8pWW5roo3w4lxnnoanigGZkJJVEHxBFJc5N/MYthhEJPVT9IwRpzXj9NCVCL7etfVk6Hv7LZk/Jq1dIh0LTv3gCzUhCON947TL2+kKKXtTC8VaURU+zw="
